apiVersion: v1
kind: PersistentVolume
metadata:
  name: cert-pv
  labels:
    project: free5gc
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /tmp/free5gc-cert
    type: DirectoryOrCreate
